name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"  # каждый день в полночь
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: "Sa1tama54"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
